// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Authenticate(arg1:string):Promise<void>;

export function DownloadAssets(arg1:Array<number>,arg2:boolean,arg3:string,arg4:string):Promise<Array<main.DownloadResult>>;

export function FetchAssets():Promise<Array<main.AssetGrant>>;

export function LoadConfig():Promise<main.Config>;

export function PickDirectory():Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function TestWebhook(arg1:string):Promise<void>;
