// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate(arg1) {
  return window['go']['main']['App']['Authenticate'](arg1);
}

export function DownloadAssets(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadAssets'](arg1, arg2, arg3, arg4);
}

export function FetchAssets() {
  return window['go']['main']['App']['FetchAssets']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TestWebhook(arg1) {
  return window['go']['main']['App']['TestWebhook'](arg1);
}
